name: golangci_lint
on:
  push:
    paths-ignore:
      - 'bin/**'
      - 'images/**'
      - 'share/**'
      - '.github/**'
      - '**.md'
      - '.gitignore'
    tags:
      - v*
    branches:
      - master
      - main
      - feature/**
      - bugfix/**
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 5m
      - name: Cache Go build
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/*.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-
